language: scala

scala:
 - "2.10.5"
 
jdk:
 - oraclejdk8
 
branches:
 only:
  - master
  
notifications:
 email:
  recipients:
   - vlad@uralian.com
   
script:
 - sbt clean coverage test
 
after_success: 
 - sbt coveralls
